engines:
  duplication:
    enabled: true
    config:
      languages:
        ruby:
          mass_threshold: 18
        javascript:
          mass_threshold: 40
  rubocop:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true
ratings:
  paths:
  - app/**
  - angularjs/**
  - "**.rb"
  - "**.js"
  - "**.css"
  - "**.html"
exclude_paths:
- "test/*"
- "public/ctrp/ui/third_party_libs/*"
- "config.js"
- "features/*"
- "app/models/ability.rb"