languages:
   Ruby: true
   JavaScript: true
exclude_paths:
- "test/*"
- "public/ctrp/ui/third_party_libs/*"
- "config.js"
- "public/ctrp/ui/*"
- "angularjs/*"
- "features/*"
- "app/models/ability.rb"

engines:
  duplication:
    enabled: true
    config:
      languages:
        ruby:
          mass_threshold: 40
        javascript:
          mass_threshold: 80