engines:
  duplication:
    enabled: true
    config:
      languages:
        ruby:
        #default is 18, increased to ignore rails rest controller methods
          mass_threshold: 50
        javascript:
          mass_threshold: 100
  rubocop:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true
ratings:
  paths:
  - "**.rb"
  - "**.js"
  - "**.css"
  - "**.html"
exclude_paths:
- "test/**/*"
- "tests/**/*"
- "config.js"
- "features/"
- "app/models/ability.rb"
- "log/**/*"
- "ETL/**/*"
- "db/**/*"
- "angularjs/ui2/gulp*.js"
- "angularjs/ui2/karma.conf.js"
