exclude_paths:
- "test/*"
- "public/ctrp/ui/third_party_libs/*"
- "config.js"
- "public/ctrp/ui/*"
- "angularjs/*"
- "features/*"
- "app/models/ability.rb"

engines:
  duplication:
    enabled: true
    config:
      languages:
        ruby:
          mass_threshold: 1500
        javascript:
          mass_threshold: 200


  rubocop:
    enabled: true

ratings:
   paths:
    "**.rb"