engines:
  duplication:
    enabled: true
    config:
      languages:
        ruby:
          mass_threshold: 1500
        javascript:
          mass_threshold: 200
  rubocop:
    enabled: true
  golint:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true

ratings:
  paths:
  - app/**
  - angularjs/**
  "**.rb"
  "**.js"
  "**.css"
  "**.html"

exclude_paths:
  - "test/*"
  - "public/ctrp/ui/third_party_libs/*"
  - "config.js"
  - "features/*"
  - "app/models/ability.rb"